#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/.haconfig" ]]; then
    mkdir -p "${PWD}/.haconfig"
fi

# Create baseline configuration.yaml if missing
if [[ ! -f "${PWD}/.haconfig/configuration.yaml" ]]; then
    cat > "${PWD}/.haconfig/configuration.yaml" <<EOF
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
EOF
fi

docker run -it --name=ha --rm -p 8123:8123 --pull always -v ./custom_components:/config/custom_components:ro -v ./.haconfig:/config homeassistant/home-assistant:stable
