name: Validate

on:
  push:
    branches: [develop, master]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validate:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v6"
      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
